### ISSUE TITLE
Link suggestion

### ISSUE THREAD

**Issue by ivan-kleshnin** [KleoPetroff/dev-log#1]
Hi Kliment. Can I suggest you to check (and possibly add) a new platform I'm currently developing:
[paqmind.com](http://paqmind.com)

I see at as "freeCodeCamp" / "KhanAcademy" inspired alternative. There's a lot of valuable unique free content already (and we update almost daily). But we don't have budget for marketing so I'd like more people to find it via GitHub and awesome list like yours ;)

**Comment by KleoPetroff** [comment]
Hi @ivan-kleshnin, the platform looks really promising. Feel free to submit a PR and add it. Since there is no similar category, you should add a new one (Education Platforms for example).

**Comment by ivan-kleshnin** [comment]
Thank you! Your section links in README have the following format:

```
x. **[AMD and RequireJS](https://github.com/KleoPetroff/dev-log/blob/master/source/amd-requirejs.md)**
```

which make them work ONLY in your repo (not in forks). Can I change all of them to the shorter

```
x. **[AMD and RequireJS](./source/amd-requirejs.md)**
```

format in a separate commit?

**Comment by KleoPetroff** [comment]
Absolutely, go for it. Relative paths do seem more logical. Thank you in advance.

**Comment by ivan-kleshnin** [comment]
Sent a PR. Closing this one. 

Btw. I liked this article http://kleopetrov.me/2017/07/07/jquery-before-fundamentals/
I will show it to my students asking this question about jQuery vs JS and tools in general.
Because I also "was there" and I entirely agree with your conclusions.

**Comment by KleoPetroff** [comment]
I'm really glad you liked it. I find this question asked a lot on events and social platforms. Almost all of us have faced this situation and had to cope with it somehow. 

Choosing the right decision is difficult and I find that the hard way.  Knowing that I helped at least one developer by writing about the topic I would be more than satisfied.
